// Mock Users Data
export const users = [
  {
    id: '1',
    email: 'client@tasklink.com',
    password: 'password123',
    firstName: 'John',
    lastName: 'Smith',
    role: 'client',
    phone: '+1 234 567 8901',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    bio: 'Looking for reliable workers for home improvement tasks.',
    location: 'New York, NY',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: '2',
    email: 'worker@tasklink.com',
    password: 'password123',
    firstName: 'Sarah',
    lastName: 'Johnson',
    role: 'worker',
    phone: '+1 234 567 8902',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Professional handyman with 10+ years of experience.',
    location: 'Brooklyn, NY',
    coordinates: { lat: 40.6782, lng: -73.9442 },
    skills: ['Plumbing', 'Electrical', 'Carpentry', 'Painting'],
    hourlyRate: 45,
    rating: 4.8,
    completedTasks: 127,
    createdAt: '2024-01-10T10:00:00Z',
  },
  {
    id: '3',
    email: 'worker2@tasklink.com',
    password: 'password123',
    firstName: 'Mike',
    lastName: 'Williams',
    role: 'worker',
    phone: '+1 234 567 8903',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mike',
    bio: 'Expert cleaner and organizer. Fast and efficient.',
    location: 'Queens, NY',
    coordinates: { lat: 40.7282, lng: -73.7949 },
    skills: ['Cleaning', 'Organizing', 'Moving Help'],
    hourlyRate: 35,
    rating: 4.6,
    completedTasks: 89,
    createdAt: '2024-01-12T10:00:00Z',
  },
  {
    id: '4',
    email: 'admin@tasklink.com',
    password: 'password123',
    firstName: 'Admin',
    lastName: 'User',
    role: 'admin',
    phone: '+1 234 567 8900',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    bio: 'System administrator',
    location: 'New York, NY',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    createdAt: '2024-01-01T10:00:00Z',
  },
  {
    id: '5',
    email: 'client2@tasklink.com',
    password: 'password123',
    firstName: 'Emily',
    lastName: 'Davis',
    role: 'client',
    phone: '+1 234 567 8904',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emily',
    bio: 'Homeowner looking for help with renovation.',
    location: 'Manhattan, NY',
    coordinates: { lat: 40.7831, lng: -73.9712 },
    createdAt: '2024-01-18T10:00:00Z',
  },
];

// Mock Tasks Data
export const tasks = [
  {
    id: '1',
    clientId: '1',
    title: 'Fix leaking kitchen faucet',
    description: 'My kitchen faucet has been leaking for a week. Need someone to fix it ASAP. The leak is coming from the base of the faucet.',
    category: 'Plumbing',
    budget: 150,
    location: 'New York, NY',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    urgency: 'high',
    requiredSkills: ['Plumbing'],
    images: [],
    status: 'published',
    createdAt: '2024-01-20T10:00:00Z',
    updatedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: '2',
    clientId: '1',
    title: 'Paint living room walls',
    description: 'Need to paint my living room walls. About 400 sq ft area. Color will be provided.',
    category: 'Painting',
    budget: 300,
    location: 'Brooklyn, NY',
    coordinates: { lat: 40.6782, lng: -73.9442 },
    urgency: 'medium',
    requiredSkills: ['Painting'],
    images: [],
    status: 'in_progress',
    workerId: '2',
    assignedAt: '2024-01-18T10:00:00Z',
    createdAt: '2024-01-17T10:00:00Z',
    updatedAt: '2024-01-18T10:00:00Z',
  },
  {
    id: '3',
    clientId: '5',
    title: 'Deep clean 3-bedroom apartment',
    description: 'Moving out clean needed for 3-bedroom apartment. Include kitchen, bathrooms, and windows.',
    category: 'Cleaning',
    budget: 250,
    location: 'Manhattan, NY',
    coordinates: { lat: 40.7831, lng: -73.9712 },
    urgency: 'high',
    requiredSkills: ['Cleaning'],
    images: [],
    status: 'assigned',
    workerId: '3',
    assignedAt: '2024-01-19T10:00:00Z',
    createdAt: '2024-01-19T10:00:00Z',
    updatedAt: '2024-01-19T10:00:00Z',
  },
  {
    id: '4',
    clientId: '5',
    title: 'Install ceiling fan',
    description: 'Need help installing a new ceiling fan in the bedroom. Electrical work may be required.',
    category: 'Electrical',
    budget: 200,
    location: 'Queens, NY',
    coordinates: { lat: 40.7282, lng: -73.7949 },
    urgency: 'low',
    requiredSkills: ['Electrical', 'Installation'],
    images: [],
    status: 'published',
    createdAt: '2024-01-21T10:00:00Z',
    updatedAt: '2024-01-21T10:00:00Z',
  },
  {
    id: '5',
    clientId: '1',
    title: 'Build wooden bookshelf',
    description: 'Custom bookshelf needed for home office. Approximately 6ft tall, 4ft wide.',
    category: 'Carpentry',
    budget: 400,
    location: 'New York, NY',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    urgency: 'medium',
    requiredSkills: ['Carpentry'],
    images: [],
    status: 'completed',
    workerId: '2',
    assignedAt: '2024-01-10T10:00:00Z',
    completedAt: '2024-01-15T10:00:00Z',
    createdAt: '2024-01-08T10:00:00Z',
    updatedAt: '2024-01-15T10:00:00Z',
  },
];

// Mock Applications Data
export const applications = [
  {
    id: '1',
    taskId: '1',
    workerId: '2',
    price: 120,
    deliveryTime: '2 days',
    message: 'I can fix this leak quickly. Have 10 years of plumbing experience.',
    status: 'pending',
    createdAt: '2024-01-20T11:00:00Z',
  },
  {
    id: '2',
    taskId: '1',
    workerId: '3',
    price: 100,
    deliveryTime: '3 days',
    message: 'I can help fix your faucet. Available this weekend.',
    status: 'pending',
    createdAt: '2024-01-20T12:00:00Z',
  },
  {
    id: '3',
    taskId: '4',
    workerId: '2',
    price: 180,
    deliveryTime: '1 day',
    message: 'Certified electrician. Can install the fan safely and quickly.',
    status: 'pending',
    createdAt: '2024-01-21T11:00:00Z',
  },
];

// Mock Messages Data
export const conversations = [
  {
    id: '1',
    participants: ['1', '2'],
    lastMessage: {
      id: 'm1',
      senderId: '2',
      content: 'I will be there tomorrow at 10 AM.',
      createdAt: '2024-01-20T15:00:00Z',
    },
    unreadCount: 1,
    updatedAt: '2024-01-20T15:00:00Z',
  },
  {
    id: '2',
    participants: ['1', '3'],
    lastMessage: {
      id: 'm2',
      senderId: '1',
      content: 'Thank you for the quote!',
      createdAt: '2024-01-19T12:00:00Z',
    },
    unreadCount: 0,
    updatedAt: '2024-01-19T12:00:00Z',
  },
];

export const messages = [
  {
    id: 'm1',
    conversationId: '1',
    senderId: '1',
    content: 'Hi, I saw your application for the faucet job.',
    createdAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'm2',
    conversationId: '1',
    senderId: '2',
    content: 'Hello! Yes, I can fix it. When would you like me to come?',
    createdAt: '2024-01-20T10:30:00Z',
  },
  {
    id: 'm3',
    conversationId: '1',
    senderId: '1',
    content: 'Can you come tomorrow morning?',
    createdAt: '2024-01-20T14:00:00Z',
  },
  {
    id: 'm4',
    conversationId: '1',
    senderId: '2',
    content: 'I will be there tomorrow at 10 AM.',
    createdAt: '2024-01-20T15:00:00Z',
  },
];

// Mock Reviews Data
export const reviews = [
  {
    id: '1',
    taskId: '5',
    reviewerId: '1',
    revieweeId: '2',
    rating: 5,
    comment: 'Excellent work! The bookshelf is beautiful and exactly what I wanted.',
    createdAt: '2024-01-16T10:00:00Z',
  },
  {
    id: '2',
    taskId: '5',
    reviewerId: '2',
    revieweeId: '1',
    rating: 5,
    comment: 'Great client! Clear instructions and good communication.',
    createdAt: '2024-01-16T11:00:00Z',
  },
];

// Categories
export const categories = [
  'Plumbing',
  'Electrical',
  'Carpentry',
  'Painting',
  'Cleaning',
  'Moving Help',
  'Gardening',
  'Assembly',
  'Other',
];

// Urgency levels
export const urgencyLevels = [
  { value: 'low', label: 'Low', color: 'green' },
  { value: 'medium', label: 'Medium', color: 'yellow' },
  { value: 'high', label: 'High', color: 'red' },
];

// Task statuses
export const taskStatuses = [
  { value: 'draft', label: 'Draft' },
  { value: 'published', label: 'Published' },
  { value: 'assigned', label: 'Assigned' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'completed', label: 'Completed' },
  { value: 'cancelled', label: 'Cancelled' },
];

